name: vibo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  image_picker: ^0.8.1
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.7
  brasil_fields: ^1.1.4
  path: ^1.8.0
  flutter_launcher_icons: ^0.9.2
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.1
  build_runner: ^2.1.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon-app.png"